name: GitHub Metrics

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: X
          filename: metrics.plugin.achievements.svg
